### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by YangshuaiWang** [Ricky-Zhao/NEP-TiAlNb-Potential#1]
I recently came across your work and found it highly impressive. I was particularly interested in your dataset, as it could significantly benefit ongoing research in this area. Would you kindly consider publishing your dataset here?

**Comment by Ricky-Zhao** [comment]
Dear colleague, 
Thank you very much for your interest in our work. However, due to an ongoing and highly relevant follow-up project, we are not publicly sharing the training dataset at this time. Once the project is completed, we plan to make it available. 
In the meantime, you may want to check out another one of our works (General-purpose machine-learned potential for 16 elemental metals and their alloys), for which the training dataset has already been made public. 
If convenient, you can also add me on WeChat, and we can exchange ideas. Wechat ID: SapphireRQ 
Best regards,
Zhiqiang 
---- Replied Message ----
***@***.***>Date11/28/2024 ***@***.***>***@***.***>Subject[Ricky-Zhao/NEP-TiAlNb-Potential] Dataset (Issue #1)
I recently came across your work and found it highly impressive. I was particularly interested in your dataset, as it could significantly benefit ongoing research in this area. Would you kindly consider publishing your dataset here?
